name: Deploy main

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  AWS_REGION: ap-southeast-2 # Change this to your AWS region

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: backend
        uses: ./.github/actions/backend

      - name: frontend
        uses: ./.github/actions/frontend

  deploy:
    name: Deploy to AWS
    needs:
      - build
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Required for OIDC authentication
      contents: read # Required for checkout

    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: "moonrepo/setup-toolchain@v0"

      - name: Deploy to AWS
        shell: bash
        run: moon run backend:deploy
        env:
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
