name: Deploy main

on:
  push:
    branches: [main]

env:
  AWS_REGION: ap-southeast-2 # Change this to your AWS region

jobs:
  backend-checks:
    uses: ./.github/actions/backend.yml

  frontend-checks:
    uses: ./.github/actions/frontend.yml

  deploy:
    name: Deploy to AWS
    needs:
      - backend-checks
      - frontend-checks
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Required for OIDC authentication
      contents: read # Required for checkout

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to AWS
        run: moon run backend:deploy
        env:
          AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
