name: Pull Request Checks

on:
  pull_request:
    branches: [main]

jobs:
  checkout:
    uses: actions/checkout@v4

  backend:
    uses: ./.github/actions/backend.yml

  frontend:
    uses: ./.github/actions/frontend.yml
