name: Pull Request Checks

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

jobs:
  build-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: backend
        uses: ./.github/actions/backend

      - name: frontend
        uses: ./.github/actions/frontend
